# Generated by Django 5.1 on 2024-08-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Track',
            new_name='Tracks',
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
    ]
